language: node_js
node_js:
  - 0.10

before_script:
  - npm install -g grunt-cli
  - "./node_modules/bower/bin/bower install"
  - "export DISPLAY=:99.0" 
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5

env:
  global:
    - secure: n8x41C7M+bPdE/tiK0RTq6HQyh0+fz3H+1ZMkR6du2zFdzVGbiOhmSgwz4J7lGkS++SzHv8D3CUP5cRBgeuiAc/VYYNK2uZ3sSVhk5PRc9Xp94F2PtvI0BL9x2+7F18ZPpQI+n13q2lo4+mDvxXScjZsufqhW+rDuDGwpUpC7cI=
    - secure: i5o40z8ozug8fepmTVYc/JoyCfwtHG8V+rKtIIJiGyg2iGoVBsz8SjRWgvgVxpFP0G1MsaWPTV13aJccshW7/aW+TlnuTyv8BTfH607aFEoPvVMVzmeIg06MlSPtSZGGEtGIz5p8WARYzLbiiOgCgF/vZmUaU8xjrRpAk8RKXd4=
